<a href="https://colab.research.google.com/github/itsmecelyssa/Linear-Algebra-58020/blob/main/Coding_Activity_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##**Python Program to Inverse a 3x3 (Matrix A)**

In [26]:
#Matrix A = ([[6,1,1],[4,-2,5],[2,8,7]])
import numpy as np
A = np.array([[6,1,1],[4,-2,5],[2,8,7]]) #I copied the professor given on 3x3 matrix. I tried to change it to 1-9 but the output became error.
print(A,"\n") #It will show the components of Matrix A or the particular code cell
B = np.linalg.inv(A)
print(B)

[[ 6  1  1]
 [ 4 -2  5]
 [ 2  8  7]] 

[[ 0.17647059 -0.00326797 -0.02287582]
 [ 0.05882353 -0.13071895  0.08496732]
 [-0.11764706  0.1503268   0.05228758]]


##**Python Program to Transpose a 3x3 (Matrix A)**

In [27]:
A = np.array([[6,1,1],[4,-2,5],[2,8,7]])
print(A,"\n")
B = np.transpose(A)
print(B)

[[ 6  1  1]
 [ 4 -2  5]
 [ 2  8  7]] 

[[ 6  4  2]
 [ 1 -2  8]
 [ 1  5  7]]


##**Python Program to Inverse a 4x4 (Matrix B)**

In [30]:
#Matrix B = ([[6,1,1,4],[4,-2,5,-3],[2,8,7,6],[-1,9,5,2]])
import numpy as np
B = np.array([[6,1,1,4],[4,-2,5,-3],[2,8,7,6],[-1,9,5,2]])
print(B,"\n") #It will show the components of Matrix B or the particular code cell
C = np.linalg.inv(A)
print(C)

[[ 6  1  1  4]
 [ 4 -2  5 -3]
 [ 2  8  7  6]
 [-1  9  5  2]] 

[[ 0.2059448   0.04953999 -0.15428167  0.12526539]
 [ 0.11677282 -0.02689314 -0.17338995  0.2462845 ]
 [-0.14861996  0.09483369  0.19037509 -0.13163482]
 [-0.05095541 -0.09129512  0.22717622 -0.21656051]]


##**Python Program to Transpose a 4x4 (Matrix B)**

In [31]:
B = np.array([[6,1,1,4],[4,-2,5,-3],[2,8,7,6],[-1,9,5,2]])
print(B,"\n")
C = np.transpose(B)
print(C)

[[ 6  1  1  4]
 [ 4 -2  5 -3]
 [ 2  8  7  6]
 [-1  9  5  2]] 

[[ 6  4  2 -1]
 [ 1 -2  8  9]
 [ 1  5  7  5]
 [ 4 -3  6  2]]
