<a href="https://colab.research.google.com/github/itsmecelyssa/Linear-Algebra-58020/blob/main/Final_Exam.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#**Final Exam**

##**Problem 1. Student A, Student B, and Student C have a total of Php 89 cash in their banks. Student A has 6 less than Student C. Student B has 3 times what Student C has. How much does each student have? (30 points)**

In [24]:
import numpy as np
A = np.array([[1, 1, 1],[1, 0, 4],[0, 0, 5]])
print(f'Matrix A:\n {A}')
print()
B = np.array([[89],[89],[95]])
print(f'Matrix A:\n {A}')
C = np.linalg.inv(A).dot(B)
print(f'\nInverse of Matrix A:\n{C}')

Matrix A:
 [[1 1 1]
 [1 0 4]
 [0 0 5]]

Matrix A:
 [[1 1 1]
 [1 0 4]
 [0 0 5]]

Inverse of Matrix A:
[[13.]
 [57.]
 [19.]]


##**Problem 2. Solve each system: (30 points)**

In [25]:
A = np.array([[3,-1,1],[9,-3,3],[-12,4,-4]])
print(A)
B = np.array([[5],[15],[-20]])
print(B)

#Compute the pseudo inverse of A
#Computationally intensive for large problems
Apinv = np.linalg.pinv(A)

#Apply the pseudo-inverse to the rhs
#Vector to obtain the `solution'
x = Apinv.dot(B)
print(x)

[[  3  -1   1]
 [  9  -3   3]
 [-12   4  -4]]
[[  5]
 [ 15]
 [-20]]
[[ 1.36363636]
 [-0.45454545]
 [ 0.45454545]]


##**Problem 3. Consider the matrix, (40 points)**

In [26]:
import numpy as np
from numpy.linalg import eig
A = np.array([[8,5,-6],[-12,-9,12],[-3,-3,5]])
print(A)

w,v = np.linalg.eig(A) 
print("The eigenvalue/s is/are:\n",w.round())
print("The eigenvector/s is/are:\n",v.round())

[[  8   5  -6]
 [-12  -9  12]
 [ -3  -3   5]]
The eigenvalue/s is/are:
 [-1.  3.  2.]
The eigenvector/s is/are:
 [[ 0. -1.  1.]
 [-1.  1.  0.]
 [-0. -0.  1.]]
