<a href="https://colab.research.google.com/github/itsmecelyssa/Linear-Algebra-58020/blob/main/Midterm_Exam.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#**Riego de Dios, Celyssa Chryse**

##**Question 1.** Create a Python code that displays a square matrix whose length is 5 (10 points)

In [18]:
import numpy as np #Import library
A = np.array([[1,2,3,4,5],[2,3,4,5,1],[3,4,5,1,2],[4,5,1,2,3],[5,1,2,3,4]]) #SET OF 5X5 MATRIX
print("Square Matrix whose length is 5")
print(A)

Square Matrix whose length is 5
[[1 2 3 4 5]
 [2 3 4 5 1]
 [3 4 5 1 2]
 [4 5 1 2 3]
 [5 1 2 3 4]]


##**Question 2.** Create a Python code that displays a square matrix whose elements below the principal diagonal are zero (10 points)

In [24]:
import numpy as np 
B = np.triu([[1,2,3,4,5],[2,3,4,5,1],[3,4,5,1,2],[4,5,1,2,3],[5,1,2,3,4]])
print("Square Matrix whose elements below the principal diagonal are zero")
print(B)

Square Matrix whose elements below the principal diagonal are zero
[[1 2 3 4 5]
 [0 3 4 5 1]
 [0 0 5 1 2]
 [0 0 0 2 3]
 [0 0 0 0 4]]


##**Question 3.** Create a Python code that displays a square matrix which is symmetrical (10 points)

In [38]:
import numpy as np 
F = np.array([[1,2,3],[2,3,3],[3,4,-2]])
print("Symmetric form of Matrix")
print(F)
G = np.transpose(F)
print("Transpose of the Matrix")
print(G)

Symmetric form of Matrix
[[ 1  2  3]
 [ 2  3  3]
 [ 3  4 -2]]
Transpose of the Matrix
[[ 1  2  3]
 [ 2  3  4]
 [ 3  3 -2]]


##**Question 4.** What is the inverse of matrix C? Show your solution by python coding. (20 points)

In [20]:
#Python Program to Inverse a 3x3 Matrix C = ([[1,2,3],[2,3,3],[3,4,-2]])
C = np.array([[1,2,3],[2,3,3],[3,4,-2]])
print(C,"\n")
D = np.linalg.inv(C)
print(D)

[[ 1  2  3]
 [ 2  3  3]
 [ 3  4 -2]] 

[[-3.6  3.2 -0.6]
 [ 2.6 -2.2  0.6]
 [-0.2  0.4 -0.2]]


##**Question 5.** What is the determinant of the given matrix in Question 4? Show your solution by python coding. (20 points)

In [40]:
import numpy as np
C = np.array([[1,2,3],[2,3,3],[3,4,-2]])
print(C,"\n")
H = np.linalg.det(C)
print(round(H))

[[ 1  2  3]
 [ 2  3  3]
 [ 3  4 -2]] 

5


##**Question 6.** Find the roots of the linear equations by showing its python codes (30 points)

In [41]:
import numpy as np
A = np.array([[5,4,1],[10,9,4],[10,13,15]])
print(A,"\n")
A_ = np.linalg.inv(A)
print(A_,"\n")
B = np.array([[3.4],[8.8],[19.2]])
print(B,"\n")

AA_ = np.dot(A,A_)
print(AA_,"\n")
BA_ = np.dot(A_,B)
print(BA_)

[[ 5  4  1]
 [10  9  4]
 [10 13 15]] 

[[ 5.53333333 -3.13333333  0.46666667]
 [-7.33333333  4.33333333 -0.66666667]
 [ 2.66666667 -1.66666667  0.33333333]] 

[[ 3.4]
 [ 8.8]
 [19.2]] 

[[ 1.00000000e+00 -4.44089210e-16 -1.66533454e-16]
 [-1.77635684e-15  1.00000000e+00 -2.22044605e-16]
 [-2.22044605e-15 -1.33226763e-15  1.00000000e+00]] 

[[0.2]
 [0.4]
 [0.8]]
