<a href="https://colab.research.google.com/github/itsmecelyssa/Linear-Algebra-58020/blob/main/Practical_Lab_Exam_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## **Problem 1**

In [105]:
import numpy as np
W = np.array ([[1,-3],[2,-2],[3,1]])
X = np.array ([[3,2,1],[-1,2,3],[2,-1,1]])
Y = np.array ([[1,2,0],[0,-1,2]])
Z = np.array ([[0,1],[2,3]])

print('Vector W is' '\n', W)
print('Vector X is' '\n', X)
print('Vector Y is' '\n', Y)
print('Vector Z is' '\n', Z)

Vector W is
 [[ 1 -3]
 [ 2 -2]
 [ 3  1]]
Vector X is
 [[ 3  2  1]
 [-1  2  3]
 [ 2 -1  1]]
Vector Y is
 [[ 1  2  0]
 [ 0 -1  2]]
Vector Z is
 [[0 1]
 [2 3]]


In [106]:
W = np.array ([[1,-3],[2,-2],[3,1]])
Y = np.array ([[1,2,0],[0,-1,2]])

print('Vector W is' '\n', W)
print('Vector Y is' '\n', Y)

Vector W is
 [[ 1 -3]
 [ 2 -2]
 [ 3  1]]
Vector Y is
 [[ 1  2  0]
 [ 0 -1  2]]


In [107]:
import numpy as np
W = np.array ([[1,-3],[2,-2],[3,1]])

print('type of array :', W.dtype)
print('shape of array :', W.shape)
print('dimension of array :', W.ndim)

type of array : int64
shape of array : (3, 2)
dimension of array : 2


In [108]:
import numpy as np
Y = np.array ([[1,2,0],[0,-1,2]])

print('type of array :', Y.dtype)
print('shape of array :', Y.shape)
print('dimension of array :', Y.ndim)

type of array : int64
shape of array : (2, 3)
dimension of array : 2


In [109]:
W = np.array ([[1,-3],[2,-2],[3,1]])
print(pool.shape)
print(pool.size)
print(pool.ndim)

(2,)
2
1


In [110]:
Y = np.array ([[1,2,0],[0,-1,2]])
print(pool.shape)
print(pool.size)
print(pool.ndim)

(2,)
2
1


In [111]:
output = np.dot(W,Y)
print(output)

[[ 1  5 -6]
 [ 2  6 -4]
 [ 3  5  2]]


In [112]:
R = Z + Z
print(R)

[[0 2]
 [4 6]]


In [113]:
R = np.add(Z,Z)
R

array([[0, 2],
       [4, 6]])

In [114]:
X = np.array ([[3,2,1],[-1,2,3],[2,-1,1]])
C = 3*X
C

array([[ 9,  6,  3],
       [-3,  6,  9],
       [ 6, -3,  3]])

## **Problem 2**

In [115]:
import numpy as np
W = np.array ([[1,-3],[2,-2],[3,1]])
X = np.array ([[3,2,1],[-1,2,3],[2,-1,1]])
Y = np.array ([[1,2,0],[0,-1,2]])
Z = np.array ([[0,1],[2,3]])

print('Vector W is' '\n', W)
print('Vector X is' '\n', X)
print('Vector Y is' '\n', Y)
print('Vector Z is' '\n', Z)

Vector W is
 [[ 1 -3]
 [ 2 -2]
 [ 3  1]]
Vector X is
 [[ 3  2  1]
 [-1  2  3]
 [ 2 -1  1]]
Vector Y is
 [[ 1  2  0]
 [ 0 -1  2]]
Vector Z is
 [[0 1]
 [2 3]]


In [116]:
output = np.dot(W,Y)
print(output)

[[ 1  5 -6]
 [ 2  6 -4]
 [ 3  5  2]]


In [117]:
print("Problem 2A")
YW = np.dot(Y,W)
A = np.power(YW,2)
print(A)
print("False")

Problem 2A
[[25 49]
 [16 16]]
False


In [118]:
print("Problem 2B")
B = np.subtract(output,X)
print(B)
print("True")

Problem 2B
[[-2  3 -7]
 [ 3  4 -7]
 [ 1  6  1]]
True


In [119]:
print("Problem 2C")
C = np.dot(Y,W)
L = np.subtract(C,Z^2)
print(L)
print("False")

Problem 2C
[[  3 -10]
 [  4   3]]
False
