<a href="https://colab.research.google.com/github/itsmecelyssa/Linear-Algebra-58020/blob/main/Prelim_Exam.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## **Riego de Dios, Celyssa Chryse**

### **Question 1**

In [18]:
import numpy as np
C = np.eye(4)
print(C)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


### **Question 2**

In [19]:
import numpy as np
C = np.eye(4)
print(C*2)

[[2. 0. 0. 0.]
 [0. 2. 0. 0.]
 [0. 0. 2. 0.]
 [0. 0. 0. 2.]]


### **Question 3**

In [20]:
import numpy as np
A = np.array([2,7,4])
B = np.array([3,9,8])
output = np.cross(A,B)
print(output)

[20 -4 -3]
