<a href="https://colab.research.google.com/github/itsmecelyssa/Linear-Algebra-58020/blob/main/Python_Exercise_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Vector Spaces and Its Operations**

In [4]:
import numpy as np
A = np.array ([4,3])
B = np.array ([2,-5])

print('Vector A is', A)
print('Vector B is', B)

Vector A is [4 3]
Vector B is [ 2 -5]


In [26]:
R = np.subtract(A,B)
R

array([ 1, -4])

In [5]:
import numpy as np
ball1 = np.array ([1,2,3])
ball2 = np.array ([0,1,-1])
pool = np.array ([ball1,ball2])
pool.shape

(2, 3)

In [25]:
import numpy as np
ball1 = np.array ([1,2,3])
ball2 = np.array ([0,1,-1])
pool = np.array ([ball1,ball2])
print(pool.shape)
print(pool.size)

(2, 3)
6


In [6]:
import numpy as np
ball1 = np.array ([1,2,3])
ball2 = np.array ([0,1,-1])
pool = np.array ([ball1,ball2])
pool.shape
pool.ndim

2

In [7]:
U = np.array ([[1,2,3,],[4,5,6]])
U

array([[1, 2, 3],
       [4, 5, 6]])

In [8]:
U = np.array ([[1,2,3,],[4,5,6]])
U.shape

(2, 3)

In [9]:
U = np.array ([[1,2,3,],[4,5,6]])
U.ndim

2

In [10]:
U = np.array ([[1,2,3,],[4,5,6]])
U.size

6

In [11]:
U = np.array ([[1,2,3,],[4,5,6]])
U
U.size

6

# **Addition of Vectors**

In [12]:
addend1 = np.array([0,0,0])
addend2 = np.array([1,1,0])
sum = addend1 + addend2
sum

array([1, 1, 0])

In [13]:
addend1 = np.array([0,0,0])
addend2 = np.array([1,1,0])
resultant = addend1 + addend2
resultant

array([1, 1, 0])

# **Subtraction of Vector**

In [14]:
#You will substract the components of addend2 from addend1 : addentd - addend2
difference = addend1 - addend2
difference

array([-1, -1,  0])

In [18]:
difference2 = np.subtract(addend1,addend2)
difference2

array([-1, -1,  0])

# **Scaling**

In [19]:
A = np.array([1,5,8,9])
S = 5*A
S

array([ 5, 25, 40, 45])

# **Cross Product**

In [21]:
A = np.array([2,3])
B = np.array([1,7])

#Compute the cross product of A and B
cross = np.cross(A,B)
print(cross)

11


In [22]:
A = np.array([2,3,4])
B = np.array([1,7,1])

#Compute the cross product of A and B
cross = np.cross(A,B)
print(cross)

[-25   2  11]


In [23]:
import numpy as np
A = np.array([2,3])
B = np.array([1,7])

#Compute the dot product of A and B
dot = np.dot(A,B)
print(dot)

23
