<a href="https://colab.research.google.com/github/itsmecelyssa/Linear-Algebra-58020/blob/main/Python_Exercise_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Vector Spaces and Its Operations**

In [84]:
import numpy as np
A = np.array ([4,3])
B = np.array ([2,-5])

print('Vector A is', A)
print('Vector B is', B)

Vector A is [4 3]
Vector B is [ 2 -5]


In [85]:
import numpy as np
ball1 = np.array ([1,2,3])
ball2 = np.array ([0,1,-1])
pool = np.array ([ball1,ball2])
pool.shape

(2, 3)

In [86]:
import numpy as np
ball1 = np.array ([1,2,3])
ball2 = np.array ([0,1,-1])
pool = np.array ([ball1,ball2])
print(pool.shape)
print(pool.size)

(2, 3)
6


In [87]:
import numpy as np
ball1 = np.array ([1,2,3])
ball2 = np.array ([0,1,-1])
pool = np.array ([ball1,ball2])
pool.shape
pool.ndim

2

In [88]:
U = np.array ([[1,2,3,],[4,5,6]])
U

array([[1, 2, 3],
       [4, 5, 6]])

In [89]:
U = np.array ([[1,2,3,],[4,5,6]])
U.shape

(2, 3)

In [90]:
U = np.array ([[1,2,3,],[4,5,6]])
U.ndim

2

In [91]:
U = np.array ([[1,2,3,],[4,5,6]])
U.size

6

In [92]:
U = np.array ([[1,2,3,],[4,5,6]])
U
U.size

6

# **Addition of Vectors**

In [93]:
import numpy as np
A = np.array ([4,3])
B = np.array ([2,-5])

print('Vector A is', A)
print('Vector B is', B)

Vector A is [4 3]
Vector B is [ 2 -5]


In [94]:
R = np.add(A,B)
R

array([ 6, -2])

In [95]:
addend1 = np.array([0,0,0])
addend2 = np.array([1,1,0])
sum = addend1 + addend2
sum

array([1, 1, 0])

In [96]:
addend1 = np.array([0,0,0])
addend2 = np.array([1,1,0])
resultant = addend1 + addend2
resultant

array([1, 1, 0])

# **Subtraction of Vector**

In [97]:
import numpy as np
A = np.array ([4,3])
B = np.array ([2,-5])

print('Vector A is', A)
print('Vector B is', B)

Vector A is [4 3]
Vector B is [ 2 -5]


In [98]:
R = np.subtract(A,B)
R

array([2, 8])

In [99]:
#You will substract the components of addend2 from addend1 : addentd - addend2
difference = addend1 - addend2
difference

array([-1, -1,  0])

In [100]:
difference2 = np.subtract(addend1,addend2)
difference2

array([-1, -1,  0])

# **Scaling**

In [101]:
A = np.array([1,5,8,9])
S = 5*A
S

array([ 5, 25, 40, 45])

In [102]:
A = np.array([1,5,8,9])
S = np.multiply(5,A)
S

array([ 5, 25, 40, 45])

# **Vector Cross Product**

In [103]:
import numpy as np
#initialize arrays

A = np.array([2,3])
B = np.array([1,7])
#Compute the cross product
#(2x7),(3,1) = (14-3) = 11
output = np.cross(A,B)
print(output)

11


In [104]:
A = np.array([2,3])
B = np.array([1,7])

#Compute the cross product of A and B
cross = np.cross(A,B)
print(cross)

11


In [105]:
A = np.array([2,3,4])
B = np.array([1,7,0])

#Compute the cross product of A and B
cross = np.cross(A,B)
print(cross)

[-28   4  11]


In [106]:
output = np.dot(A,B) #comput the dot product
print(output) #(2x1) = 2 (3x7)= 21 (4x0)= 0

23


In [107]:
A = np.array([2,7])
B = np.array([1,7])

output = np.cross(A,B)
print(output)

7


In [108]:
output = np.dot(A,B) #compute the dot product
print(output)

51


In [109]:
import numpy as np
A = np.array([2,3])
B = np.array([1,7])

#Compute the dot product of A and B
dot = np.dot(A,B)
print(dot)

23
