<a href="https://colab.research.google.com/github/itsmecelyssa/Linear-Algebra-58020/blob/main/Python_Exercise_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Matrix and Its Operations

In [4]:
import numpy as np
# 1 sum A + B
A = np.array([[-5,0],[4,1]])
B = np.array([[6,-3],[2,3]])
print(A+B)

[[ 1 -3]
 [ 6  4]]


In [2]:
import numpy as np
# 2 difference1 A - B
A = np.array([[-5,0],[4,1]])
B = np.array([[6,-3],[2,3]])
print(A-B)

[[-11   3]
 [  2  -2]]


In [5]:
import numpy as np
# 3 difference2 B - B
B = np.array([[6,-3],[2,3]])
B = np.array([[6,-3],[2,3]])
print(B-B)

[[0 0]
 [0 0]]
